### ISSUE TITLE
Use swagger (Swashbuckle ) with ASP.NET core 2.2 and IIS virtual applications 

### ISSUE THREAD

**Issue by EnricoMassoneDeltatre** [aspnet/AspNetCore.Docs.it-it#30]
Hi, 

I'm currently testing the integration between ASP.NET core and swagger by using the `Swashbuckle.AspNetCore` nuget package.

My current test environment is the following:

- ASP.NET core 2.2 web application with one api controller
- the development machine is a windows 10 machine
- the installed version of IIS is IIS 10

I'm testing my application by using a virtual application under the IIS default web site. The virtual application has an alias of `test-swagger`. By following the documentation I configured the swagger middleware in the following manner (**notice the . (dot) character at the beginning of the swagger endpoint**): 

```
app.UseSwaggerUI(c =>
      {
        c.SwaggerEndpoint("./swagger/v1/swagger.json", "My API V1");
      });
```

By configuring swagger this way the swagger UI does **not** work as expected, a pop-up is showed when the path `/swagger` is called and the message showed states that the swagger UI is not able to find the swagger.json file. 

By following [this blog](https://bartwullems.blogspot.com/2018/08/aspnet-coreswagger-error-when-using.html) I finally solved my issue. Basically, the only difference is that **two . (dot) characters are required in the swagger endpoint configuration** (while the official docs reports that just one dot character must be used in the swagger endpoint as a prefix). 

To summarize, the working configuration for me is the following (**notice the two . (dot) characters at the beginning of the swagger endpoint**): 

```
app.UseSwaggerUI(c =>
      {
        c.SwaggerEndpoint("../swagger/v1/swagger.json", "My API V1");
      });
```

Is there an error in the official docs ? Am I missing something ? 

Thanks for helping !

---
#### Dettagli del documento

⚠ *Non modificare questa sezione. È necessaria per i collegamenti relativi ai problemi tra docs.microsoft.com ➟ GitHub.*

* ID: 14fce65f-1337-58cb-2193-8d8e0e62792d
* Version Independent ID: 59222460-a971-e76e-4fe9-23d4d7d768ee
* Content: [Introduzione a Swashbuckle e ad ASP.NET Core](https://docs.microsoft.com/it-it/aspnet/core/tutorials/getting-started-with-swashbuckle?view=aspnetcore-2.2&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/getting-started-with-swashbuckle.md](https://github.com/aspnet/AspNetCore.Docs.it-it/blob/live/aspnetcore/tutorials/getting-started-with-swashbuckle.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @zuckerthoben
* Microsoft Alias: **scaddie**

**Comment by CeciAc** [comment]
Hello, @EnricoMassoneDeltatre 

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
