### ISSUE TITLE
Using missing

### ISSUE THREAD

**Issue by MarGraz** [aspnet/AspNetCore.Docs.it-it#34]
In this code snippet https://docs.microsoft.com/it-it/aspnet/core/tutorials/first-web-api?view=aspnetcore-2.2&tabs=visual-studio#register-the-database-context some using are missing, and also some code is missing:

using Microsoft.EntityFrameworkCore;
using TodoApi.Models;

***
Code:

Services.AddDbContext&lt;YOURMODEL&gt;(opt =&gt; opt.UseInMemoryDatabase("TodoList"));

---
#### Dettagli del documento

⚠ *Non modificare questa sezione. È necessaria per i collegamenti relativi ai problemi tra docs.microsoft.com ➟ GitHub.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Esercitazione: Creare un'API Web con ASP.NET Core](https://docs.microsoft.com/it-it/aspnet/core/tutorials/first-web-api?view=aspnetcore-2.2&tabs=visual-studio#register-the-database-context)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/aspnet/AspNetCore.Docs.it-it/blob/live/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
I'm sorry for the inconvenience. This is a system wide problem that's tracked in https://github.com/aspnet/AspNetCore.Docs/issues/13143.

**Comment by Rick-Anderson** [comment]
Please close.

**Comment by CeciAc** [comment]
Hello, @MarGraz 

Your contribution is much appreciated. Our team reviewed your feedback and it appears that this issue has been already logged.
Please review issue https://github.com/aspnet/AspNetCore.Docs/issues/13143
For this reason we are closing this issue since it is duplicated.

Kind regards,
Microsoft DOCS International Team
