### ISSUE TITLE
Unable to run debug from Chrome/Edge Beta  Dev Tools

### ISSUE THREAD

**Issue by zaffaste** [aspnet/AspNetCore.Docs.it-it#37]
I followed all the steps here "https://docs.microsoft.com/it-it/aspnet/core/blazor/debug?view=aspnetcore-3.0#procedure" but I keep getting error: "Debugging connection was closed. Reason: WebSocket disconnected". Anyone could help me?

---
#### Dettagli del documento

⚠ *Non modificare questa sezione. È necessaria per i collegamenti relativi ai problemi tra docs.microsoft.com ➟ GitHub.*

* ID: ec2f61c7-9f51-6735-e328-3c7b495d70c3
* Version Independent ID: 4d06e565-282d-6387-aa90-cb2c2986d35a
* Content: [Debug ASP.NET Core Blazer](https://docs.microsoft.com/it-it/aspnet/core/blazor/debug?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/blazor/debug.md](https://github.com/aspnet/AspNetCore.Docs.it-it/blob/live/aspnetcore/blazor/debug.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by srvbpigh** [comment]
Hello, @zaffaste
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @zaffaste

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
