### ISSUE TITLE
Please fix and integrate the content

### ISSUE THREAD

**Issue by unsafecode** [aspnet/AspNetCore.Docs.it-it#38]
I'm currently migrating a large ASP.NET 2.2 app to 3.0, and I was referring to this page for guidance. However, I found lots of important information missing:

* The collapsible panel under "Remove obsolete package references" hides most of the relevant content. Additionally, the layout of deprecated packages is unreadabl.e
* There must be a specific section on how to upgrade existing Class Libraries to leverage ASP.NET Core 3.0 (cross-targeting, #ifdef, etc...)
* Please list all the API breaking changes for ASP.NET Core 3.0. For instance, AllowSynchronousIO is mentioned, but not the fact it breaks Microsoft.AspNetCore.ResponseCaching (just to mention one), and requires it to enable backward compatibility.
* There must be another section about 3rd party libraries (eg. SwashBuckle.Swagger) that need to be migrated as well (at least add the link)

---
#### Dettagli del documento

⚠ *Non modificare questa sezione. È necessaria per i collegamenti relativi ai problemi tra docs.microsoft.com ➟ GitHub.*

* ID: 76f39eec-9dd1-6167-56ec-47b26e0b5063
* Version Independent ID: f9f2b0f3-01eb-cf58-8767-194fe0fc0e44
* Content: [Eseguire la migrazione da ASP.NET Core 2,2 a 3,0](https://docs.microsoft.com/it-it/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/migration/22-to-30.md](https://github.com/aspnet/AspNetCore.Docs.it-it/blob/live/aspnetcore/migration/22-to-30.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by srvbpigh** [comment]
Hello, @unsafecode
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @unsafecode

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/aspnet/AspNetCore.Docs/issues/14599

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
