### ISSUE TITLE
Check MySql support

### ISSUE THREAD

**Issue by meriturva** [aspnet/AspNetCore.Docs.it-it#41]
With version 8.0.18: https://dev.mysql.com/doc/relnotes/connector-net/en/news-8-0-18.html
seems that .net core 3 is supported now!

---
#### Dettagli del documento

⚠ *Non modificare questa sezione. È necessaria per i collegamenti relativi ai problemi tra docs.microsoft.com ➟ GitHub.*

* ID: 76f39eec-9dd1-6167-56ec-47b26e0b5063
* Version Independent ID: f9f2b0f3-01eb-cf58-8767-194fe0fc0e44
* Content: [Eseguire la migrazione da ASP.NET Core 2,2 a 3,0](https://docs.microsoft.com/it-it/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/migration/22-to-30.md](https://github.com/aspnet/AspNetCore.Docs.it-it/blob/live/aspnetcore/migration/22-to-30.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@meriturva  would you mind closing this and opening it in the english repo? This is not a localization issue.

**Comment by srvbpigh** [comment]
Hello, @meriturva
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by Rick-Anderson** [comment]
@CeciAc  if you give me permission to transfer issues, I can transfer issues like this to https://github.com/aspnet/AspNetCore.Docs

**Comment by Rick-Anderson** [comment]
@meriturva ti dispiacerebbe chiudere questo e aprirlo nel repository inglese? Questo non è un problema di localizzazione.

**Comment by meriturva** [comment]
@Rick-Anderson sure!
