### ISSUE TITLE
Ottimo contenuto

### ISSUE THREAD

**Issue by ruggeropaolobasile** [aspnet/AspNetCore.Docs.it-it#45]
Le prime battute in "In Esplora soluzioni fare clic con il pulsante destro del mouse su Controller &gt; Aggiungi &gt; Controller" sono incongruenti con l'immagine

---
#### Dettagli del documento

⚠ *Non modificare questa sezione. È necessaria per i collegamenti relativi ai problemi tra docs.microsoft.com ➟ GitHub.*

* ID: 20264150-9ac7-2b21-3314-64ffa114410f
* Version Independent ID: 3477519b-1bc2-73be-33e3-63067383d426
* Content: [Aggiungere un controller a un'app ASP.NET Core MVC](https://docs.microsoft.com/it-it/aspnet/core/tutorials/first-mvc-app/adding-controller?view=aspnetcore-3.1&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/tutorials/first-mvc-app/adding-controller.md](https://github.com/aspnet/AspNetCore.Docs.it-it/blob/live/aspnetcore/tutorials/first-mvc-app/adding-controller.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by srvbpigh** [comment]
Hello, @ruggeropaolobasile
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by ticianaciminari** [comment]
Ciao @ruggeropaolobasile:
 
Grazie per il contributo. 

I contributi sui problemi di traduzione relativi a contenuto tradotto automaticamente non vengono attualmente accettati. 

Apprezziamo il tuo feedback e i tuoi suggerimenti sul contenuto tradotto manualmente, che viene usato per il training dei motori di traduzione automatica. Nel tempo i tuoi contributi miglioreranno quindi la qualità delle traduzioni manuali e automatiche. 

Gli argomenti tradotti manualmente possono essere distinti dagli argomenti tradotti automaticamente mediante il valore "HT" per i metadati ms.translationtype, rispetto a "MT" per la traduzione automatica, nell'intestazione di ogni file di contenuto. 

Grazie per il supporto. 

Team di Microsoft DOCS Global Experience
